### ISSUE TITLE
Tree view isn't collapsed by default in ZGM missions

### ISSUE THREAD

**Issue by CreepPork** [zen-mod/ZEN#118]
https://gyazo.com/0252190dee9afc3b1b7c4e6f6b8d293e

**Comment by mharis001** [comment]
Is this after the mission gets the curator to place a respawn position? Before which everything except for the respawn modules are hidden.

If so there is no way to fix this since, these missions use `removeAllCuratorAddons` and then after a respawn is placed `addCuratorAddons`. There is no event for when curator addons change and either way, I don't think this is a big deal due to the tree collapse/expand buttons.

**Comment by mharis001** [comment]
Close?

**Comment by CreepPork** [comment]
If I'm not mistaken, Achilles works fine with the ZGM missions and the tree auto collapses. There might be a workaround possible, need to dig a bit in Achilles.
