### ISSUE TITLE
Game Master Modules deleted on Dedicated Server

### ISSUE THREAD

**Issue by DeliciousJaffa** [zen-mod/ZEN#420]
**Arma 3 Version:** `1.98 146445` (stable)
**CBA Version:** `3.15.1` (stable)
**ZEN Version:** `1.8.0` (stable)

**Mods:**
```
- CBA_A3
- ZEN
- ACE3
- ACEX
- 3CB
- RHS
```

**Description:**
Zeus game master modules can be deleted by the module init script when starting a mission as a virtual Zeus in a Dedicated Server environment. This is confirmed by checking `allCurators` which returns an empty array when loading this way, whereas loading into a normal slot then switching to zeus, they remain in the output.

**Steps to reproduce:**
Unclear on the exact order, however placings a few playable groups, with 2 game master and virtual zeus pairs is enough to trigger this.

**Where did the issue occur?**
Dedicated

**Additional information:**
This bug appears to be a bug carried over from the BIS init, specifically this "sanity check"
https://github.com/zen-mod/ZEN/blob/master/addons/modules/functions/fnc_bi_moduleCurator.sqf#L32-L36
```sqf
    // Exit if the module is not created on the server
    if (!isServer && {local _logic} && {isNull getAssignedCuratorUnit _logic}) exitwith {
        [format ["%1 is trying to create a Curator logic ModuleCurator_F.", profileName]] remoteExec ["BIS_fnc_error", 2];
        deleteVehicle _logic;
    };
```
My best guess here is that the Zeus entities are forming a "Logic" group/sideCentre that then localises to the player trying to zeus on mission start up.
It's also worth noting players get stuck with a black screen when attempting the switching slot workaround which requires unassigning curator and adding it back due to `getAssignedCuratorUnit` returning the unit, but `getAssignedCuratorLogic` returning objNull.

**RPT log file:**
No script errors, however with `allowFunctionsLog = 1;` we see the following `BIS_fnc_error` messages
```
1:19:37 "MILSIM/log: ERROR: Jaffa is trying to create curator logic ModuleCurator_F"
1:19:37 "MILSIM/log: ERROR: Jaffa is trying to create curator logic ModuleCurator_F"
```

[Sample Mission File](https://data.jaffa.cat/NUT_JAF_2020_TEST8.Malden.pbo)

**Comment by mharis001** [comment]
I was unable to reproduce the issue in local MP but, I can see why it would occur. I would need to take another look but I think it would be fine to remove this check - the code shouldn't require the logic being local to the server.

**Comment by DeliciousJaffa** [comment]
Yeah, works fine in local MP (from editor) for me too, but as soon as I put the mission on dedicated server, that condition returns true and causes the modules to be deleted.

There is further to this issue though, Virtual Zeus gets a black screen when joining a normal slot and switching to Zeus slot.
The Local EVH contains code that does fix that would fix that zeus issue but it doesn't appear to run, so I assume the locality is being changed "too early" for whatever reason.

**Comment by tyl3r99** [comment]
Ive managed to re create this in LOCAL MP 

**Reproduction steps** 
Go into editor (altis)

Place down unit i.e. officer with variable name z1
place down game master module with owner z1
Click play in MP (for some reason ZEN does not work in the editor enviroment??? (intended?)

Once your in game press Y

Go to the zeus tab and update editable objects and place it near the player or wherever you put the module. 

Delete the module in zeus 

Exit zeus 

*Now try to go back into zeus.*

**Comment by mharis001** [comment]
That's the intended behaviour that you are no longer a curator if you delete the module.

**Comment by DeliciousJaffa** [comment]
@tyl3r99 This issue is regarding the module being deleted automatically by the module init script.
You've just described how to manually delete the zeus module, that isn't relevant to this issue.

**Comment by XenithZero** [comment]
I've been recently seeing this issue on my server as well. I am not able to fix it or alter anything to make game master modules work, so I've resided to just using Achillies server-side until it's fixed. I originally thought a certain mod was disabling the modules somehow (which was actually the case a couple of weeks ago), but the issue has since returned and I haven't been able to do anything about it.

**Comment by Arcanum417** [comment]
Can replicate when starting mission with civilian slot with zeus module set as owner.

**Comment by TyroneMF** [comment]
My group has seen this issue twice, Seemingly restarting the server makes the Game Master initialize.

When the issue is present and Zeus is completely unavailable people can't ping Zeus either.

We also use ArmaZeusCache, attempts to reproduce this are pretty difficult with only 2 cases spread out across 2 months.

**Comment by mharis001** [comment]
Was unable to reproduce on a dedicated server with CBA and ZEN. The mission used was on VR with 2 playable BLUFOR fire teams and 2 Zeus virtual entities + 2 Game Master modules.

Maybe the issue becomes more prevalent with a larger amount of mods? (will try to test that)

**Comment by genjonakasone** [comment]
Bumping up, this issue is getting really annoying. It happens often without any scheme, sometimes where I have at least 2 Zeuses, there's a possibility to one of us not able to be Curator because somehow the module disconnects/deletes itself, and the only fixes are:
1. manually reasign/create/reload GM module with debug console which is bad
2. switch slot to another zeus hoping that it didn't disconnect which is even worse I guess
3. reset server/mission as long as every zeus is connected to the modules

3. seems to be the best but it can happen anytime during the mission, not only on startup. I've been trying to connect that to people using wi-fi or any type of slower internet connection, but it might be as well server lags or something with load order of scripts, dunno for real.

**Comment by mharis001** [comment]
Was able to reproduce consistently even on hosted multiplayer. That check seems unnecessary and should be removed.
