### ISSUE TITLE
Feature Request: Exec line

### ISSUE THREAD

**Issue by MGZoltan** [zen-mod/ZEN#5]
Another Achilles feature that is greatly appreciated- Upon doubleclicking a unit to get to the attributes tab, there was also an exec box to run code on a given unit. Something like this would be greatly appreciated, particularly with the ability to bookmark/favorite specific things. Achilles had a 'last used' tab, and while it was greatly useful, it was a little limited as it only stored a set quantity of ran codes.

**Comment by mharis001** [comment]
Thank you for the feature request. When going to implement this I was unsure exactly what way would be best since changes to attributes in ZEN are only applied for attributes that had a selection occur.

So, if the user was to enter code, it would execute when the user pressed ok, but the next the user opens the attributes display, should it execute again when the user presses ok? My original solution was to add a button next to the input box.

On the topic of saving executed code pieces, there needs to be limit on the number of stored items since we are storing it in `profileNamespace`. What would suggest is a good number? 20? 50?

I like the idea of bookmarking frequently used items but I am unsure how to integrate that into a UI.

**Comment by MGZoltan** [comment]
In achilles, the code-entry box is a 'one-time' use unless you load a last command through the drop-down of last used commands. So it'll pop back up empty. A button next to the input box would be kind of convenient too though.

**Comment by mharis001** [comment]
#16 will add this. Decided to go with the behaviour that exists in vanilla with requiring the OK button to execute. The code will only execute if its not empty and open as empty.

In terms of locality, I decided it might be best for QOL that the code run where the object is local since I think most of the commands that are used by Zeus' in this attribute require arguments local. This can easily be changed to be global if you think that would be better.

In terms of the history, it is currently limited to 20, but again, can be increased if you think that number is too low. For the bookmarking feature, I still need to think about how to cleanly integrate that into a UI.

Would love to you hear your thoughts on this and again thanks for the feedback.

**Comment by MGZoltan** [comment]
Excellent, thanks for this feature. I'm not exactly sure what general limitations are for a UI. On a bare minimum, assuming you're very hamstringed, I'd say a little star button that adds the current code in the exec box to a longer(?) list or just tells you if adding a new one will push out an old favorite
