### ISSUE TITLE
Ammo Slider for Infantry + Crewed Turrets.

### ISSUE THREAD

**Issue by Deuce6** [zen-mod/ZEN#568]
**Is your feature request related to a problem?**
Achilles mod as well as base Zeus has the option to refill infantry Ammo the same as health or skill sliders. This is absent from Zen for some reason and seems like a very jarring omission. 

**Solution you'd like:**
I would really like the Ammo slider to be restored, it's almost crucial if you have a squad using suppress commands with an MG. It also prevents having to delete and replace the unit if you want it to keep up the engagement or add ambiance.

**Alternatives you've considered:**
LTo delete and replace the unit when it runs dry. Manually going into arsenal to replace magazines. Having an Ammo Ural nearby and hope the AI can reply itself while I'm distracted during intensive Zeus operations.

**Additional context:**
The lack of Ammo slider is one of the main things holding back our unit from adjusting from Achilles to ZEN. It may seem trivial but I do feel it's important.  If Helicopters, Cars, Tanks have Ammo sliders, infantry should have the option too.

**Comment by mharis001** [comment]
Base game Zeus does not have an ammo slider attribute for infantry (or vehicles). The primary problem with this type of attribute for infantry is what would considered "full" ammo. For vehicles, we can consider the ammo count of the current magazines from the full versions since vehicles retain empty magazines. However, infantry units do not retain empty magazines and this method cannot be used.

Furthermore, the config defined loadout for the unit is also problematic since how do we account for changes to the loadout. What happens if the unit's loadout was changed significantly and now the ammo is set to 100%? Do we reset back to the config one, discarding the curator's changes to the loadout?

For these reasons, the _best_ solution would likely involve resetting to the config defined loadout but that has its own problems. If you just want to reset the unit's loadout, we do have a "Reset Loadout" context menu action now.

**Comment by TheRadiumDude** [comment]
You can execute this code in the init of a unit via their **Attributes** menu. This should at least allow you to keep up a constant engagement without fear of AI running out of ammo. *(Every time a unit reloads, this script adds a new magazine equivalent to the magazine they last used.)*

```sqf
_this addEventHandler ["Reloaded", {
    params ["_unit", "", "", "", "_oldMag"];
    if !(_oldMag isEqualTo []) then {
        _unit addMagazineGlobal (_oldMag select 0);
    };
}]
```

**Comment by mharis001** [comment]
For the aforementioned reasons, I don't think this will be worked on.
